// <auto-generated />
using System;
using Contigo.Quotes.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Contigo.Quotes.Migrations
{
    [DbContext(typeof(QuotesDbContext))]
    [Migration("20260905174847_AddNegotiationOutcomeSavingsOpportunityId")]
    partial class AddNegotiationOutcomeSavingsOpportunityId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contigo.Quotes.Domain.NegotiationOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("discount_percent");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("final_price");

                    b.Property<string>("LeversUsed")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("levers_used");

                    b.Property<int>("NegotiationDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("negotiation_duration_days");

                    b.Property<decimal>("OriginalQuoteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("original_quote_total");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<decimal>("RealizedSaving")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("realized_saving");

                    b.Property<Guid?>("SavingsOpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("savings_opportunity_id");

                    b.Property<decimal?>("TargetPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_price");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_negotiation_outcome");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_negotiation_outcome_tenant_id");

                    b.HasIndex("TenantId", "QuoteId")
                        .HasDatabaseName("ix_negotiation_outcome_tenant_id_quote_id");

                    b.ToTable("negotiation_outcome", (string)null);
                });

            modelBuilder.Entity("Contigo.Quotes.Domain.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("checksum");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("Geography")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("geography");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mime_type");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("processing_status");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("supplier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quote");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_quote_tenant_id");

                    b.ToTable("quote", (string)null);
                });

            modelBuilder.Entity("Contigo.Quotes.Domain.QuoteExtractionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_detail");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_id");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quote_extraction_job");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_quote_extraction_job_tenant_id");

                    b.HasIndex("TenantId", "QuoteId")
                        .HasDatabaseName("ix_quote_extraction_job_tenant_id_quote_id");

                    b.ToTable("quote_extraction_job", (string)null);
                });

            modelBuilder.Entity("Contigo.Quotes.Domain.QuoteLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("discount_percent");

                    b.Property<string>("Edition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("edition");

                    b.Property<decimal?>("ExtendedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("extended_price");

                    b.Property<decimal?>("ListPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("list_price");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unmatched")
                        .HasColumnName("match_status");

                    b.Property<decimal?>("NormalizedAnnualUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("normalized_annual_unit_price");

                    b.Property<string>("NormalizedEdition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_edition");

                    b.Property<string>("NormalizedSku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_sku");

                    b.Property<int?>("NormalizedTermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("normalized_term_months");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<string>("SourceSpan")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_span");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Term")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("term");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_quote_line");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_quote_line_tenant_id");

                    b.HasIndex("TenantId", "QuoteId")
                        .HasDatabaseName("ix_quote_line_tenant_id_quote_id");

                    b.ToTable("quote_line", (string)null);
                });

            modelBuilder.Entity("Contigo.Quotes.Domain.SkuProductMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalEdition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("canonical_edition");

                    b.Property<string>("CanonicalProductName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("canonical_product_name");

                    b.Property<string>("CanonicalSku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("canonical_sku");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedEdition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_edition");

                    b.Property<string>("NormalizedSku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_sku");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sku_product_mapping");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sku_product_mapping_tenant_id");

                    b.HasIndex("TenantId", "NormalizedSku")
                        .IsUnique()
                        .HasDatabaseName("ix_sku_product_mapping_tenant_id_normalized_sku");

                    b.ToTable("sku_product_mapping", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
