/**
 * OIDC Authorization Code + PKCE config, pure/framework-free (ADR-010, ADR-013).
 *
 * This module builds the request shapes `expo-auth-session` needs; it never
 * opens a browser or performs network I/O itself (that lives in
 * `useOidcAuth.ts`), which keeps it deterministic and unit-testable the same
 * way `web/src/auth/msalConfig.ts` tests `buildMsalConfig`/`buildLoginRequest`
 * without exercising MSAL's own redirect/PKCE plumbing.
 *
 * PKCE, not a client secret, is what authenticates the token exchange
 * (ADR-010 "no client secret anywhere (PKCE)"; ADR-013 "no client secret is
 * ever placed in the app/bundle"). `AuthRequestConfig`/`AccessTokenRequestConfig`
 * both have an optional `clientSecret` field (expo-auth-session supports
 * confidential clients too) — this module never sets it, and the accompanying
 * tests assert that structurally, mirroring web's "never carries a client
 * secret" test.
 */
import { CodeChallengeMethod, ResponseType } from 'expo-auth-session';
import type { AccessTokenRequestConfig, AuthRequestConfig } from 'expo-auth-session';
import type { MobileEnvConfig } from '../config/env';

/**
 * Scopes every sign-in requests regardless of environment. Unlike MSAL (used
 * by `web/`), which injects `openid`/`profile`/`offline_access` automatically,
 * `expo-auth-session`'s `AuthRequest` sends exactly the `scopes` array given
 * to it — so these must be listed explicitly to get back an ID token and a
 * refresh token from Entra ID's `/oauth2/v2.0/token` endpoint.
 */
export const STANDARD_OIDC_SCOPES = ['openid', 'profile', 'offline_access'] as const;

/**
 * The full scope list requested at sign-in: the standard OIDC scopes plus
 * this environment's API scopes (`MobileEnvConfig.oidcApiScopes`, ADR-010
 * placeholder `Contigo.Read`/`Contigo.Write`-shaped values).
 */
export function buildOidcScopes(env: Pick<MobileEnvConfig, 'oidcApiScopes'>): string[] {
  return [...STANDARD_OIDC_SCOPES, ...env.oidcApiScopes];
}

/**
 * Builds the `expo-auth-session` `AuthRequestConfig` for the Authorization
 * Code + PKCE flow (ADR-010 "authorization-code + PKCE", `usePKCE: true` is
 * also expo-auth-session's default — set explicitly here so the intent is
 * not implicit). `redirectUri` is deliberately a parameter, not computed
 * here: callers pass `getNativeRedirectUri()` (`../config/redirectUri`,
 * `contigo://callback`, parent story AC-1) so this module stays agnostic of
 * how the redirect URI is derived and easy to test with any value.
 */
export function buildAuthRequestConfig(
  env: Pick<MobileEnvConfig, 'oidcClientId' | 'oidcApiScopes'>,
  redirectUri: string
): AuthRequestConfig {
  return {
    clientId: env.oidcClientId,
    redirectUri,
    scopes: buildOidcScopes(env),
    responseType: ResponseType.Code,
    usePKCE: true,
    codeChallengeMethod: CodeChallengeMethod.S256,
  };
}

/**
 * Builds the `expo-auth-session` `AccessTokenRequestConfig` used to exchange
 * an authorization code for tokens at Entra ID's token endpoint. `codeVerifier`
 * (generated by the `AuthRequest` that produced `code`) is sent as the PKCE
 * `code_verifier` extra param — this, not a client secret, is what proves
 * possession of the original request (RFC 7636 §4.5).
 */
export function buildTokenExchangeConfig(
  env: Pick<MobileEnvConfig, 'oidcClientId'>,
  redirectUri: string,
  code: string,
  codeVerifier: string
): AccessTokenRequestConfig {
  return {
    clientId: env.oidcClientId,
    code,
    redirectUri,
    extraParams: {
      code_verifier: codeVerifier,
    },
  };
}
