using Contigo.Documents.Contracts.Domain;
using Contigo.Documents.Contracts.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Testcontainers.PostgreSql;

namespace Contigo.Tenancy.Tests;

/// <summary>
/// This is task E01/F04/US03/T02's CI migration check: it proves that ADR-009/AC-4's RLS
/// guarantee holds for the *deployable* schema artifact, not only for the EF Core runtime
/// migrator that <see cref="TenantRlsMigrationCheckTests"/> already covers.
///
/// `Migrations/Scripts/documents-contracts.sql` (generated by `dotnet ef migrations script
/// --idempotent`, per <c>DocumentsContractsMigrationScriptTests</c>) is the artifact an operator
/// or CI/CD deploy step actually runs against a fresh `dev`/`demo` server -- e.g. `psql -f` -- and
/// it is checked in by hand, not regenerated automatically. Nothing forces it to be regenerated
/// when a new migration is added: this test caught exactly that failure mode during this task --
/// task E01/F04/US03/T01 added the `AddTenantRowLevelSecurity` migration and proved it via
/// <c>DocumentsContractsDbContext.Database.MigrateAsync()</c>, but the checked-in script was never
/// regenerated, so it still ended at `Initial` with no RLS statements at all. A `psql -f` deploy
/// from that script would have left every tenant table world-readable across tenants despite all
/// of us-03's other tests passing. `Migrations/Scripts/documents-contracts.sql` has since been
/// regenerated as part of this task; this test is what makes a future recurrence fail the build
/// instead of shipping silently.
///
/// Tenant-scoped tables are discovered dynamically from the EF model (every
/// <see cref="TenantScopedEntity"/> subclass), exactly like <see cref="TenantRlsMigrationCheckTests"/>,
/// so this keeps checking a future tenant-scoped table's migration without anyone remembering to
/// extend this test by hand. Reading <see cref="DbContext.Model"/> only builds the model from
/// conventions/configuration in memory -- it never opens a connection -- so it is safe to call
/// before the deployable script (not EF migrations) has created any schema on the container.
/// </summary>
public sealed class TenantRlsDeployableScriptCheckTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder("pgvector/pgvector:pg16")
        .Build();

    public Task InitializeAsync() => _postgres.StartAsync();

    public Task DisposeAsync() => _postgres.DisposeAsync().AsTask();

    [Fact]
    public async Task Deployable_script_enables_forced_row_level_security_for_every_tenant_scoped_table()
    {
        var tenantScopedTables = GetTenantScopedTableNames();

        // Guards the guard (mirrors TenantRlsMigrationCheckTests): if this is ever empty, table
        // discovery itself is broken (e.g. a renamed base type) and every assertion below would
        // pass vacuously without proving anything.
        Assert.NotEmpty(tenantScopedTables);

        var script = await ReadScriptAsync();

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();

        // The exact artifact an operator or CI/CD deploy step runs -- no
        // DocumentsContractsDbContext, no EF Core runtime migrator anywhere in this call.
        await using (var apply = new NpgsqlCommand(script, connection))
        {
            await apply.ExecuteNonQueryAsync();
        }

        foreach (var table in tenantScopedTables)
        {
            var (rowSecurityEnabled, rowSecurityForced) = await ReadRowSecurityFlagsAsync(connection, table);

            Assert.True(
                rowSecurityEnabled,
                $"[ADR-009/AC-2] Deployable script Migrations/Scripts/documents-contracts.sql " +
                $"leaves tenant-scoped table \"{table}\" without ROW LEVEL SECURITY. Regenerate " +
                "it with `dotnet ef migrations script --idempotent` from " +
                "src/Contigo.Documents.Contracts after adding/changing an RLS migration.");
            Assert.True(
                rowSecurityForced,
                $"[ADR-009/AC-2] Deployable script Migrations/Scripts/documents-contracts.sql " +
                $"leaves tenant-scoped table \"{table}\" without FORCE ROW LEVEL SECURITY. " +
                "Regenerate it with `dotnet ef migrations script --idempotent` from " +
                "src/Contigo.Documents.Contracts.");

            var policyCount = await ReadPolicyCountAsync(connection, table);

            Assert.True(
                policyCount >= 1,
                $"[ADR-009/AC-4] Deployable script Migrations/Scripts/documents-contracts.sql " +
                $"leaves tenant-scoped table \"{table}\" without an RLS policy. Regenerate it " +
                "with `dotnet ef migrations script --idempotent` from " +
                "src/Contigo.Documents.Contracts after adding/changing an RLS migration.");
        }
    }

    /// <summary>
    /// Builds a <see cref="DocumentsContractsDbContext"/> over the (still schema-less) container
    /// connection purely to read <see cref="DbContext.Model"/> -- no tenant context, no migrate
    /// call, no query. See the type doc comment for why this never touches the database.
    /// </summary>
    private List<string> GetTenantScopedTableNames()
    {
        var optionsBuilder = new DbContextOptionsBuilder<DocumentsContractsDbContext>();
        DocumentsContractsDbContextOptions.Configure(optionsBuilder, _postgres.GetConnectionString());

        using var db = new DocumentsContractsDbContext(optionsBuilder.Options);

        return db.Model.GetEntityTypes()
            .Where(entityType => typeof(TenantScopedEntity).IsAssignableFrom(entityType.ClrType))
            .Select(entityType => entityType.GetTableName())
            .Where(tableName => tableName is not null)
            .Cast<string>()
            .Distinct()
            .OrderBy(tableName => tableName, StringComparer.Ordinal)
            .ToList();
    }

    /// <summary>
    /// Walks from this source file (<c>backend/tests/Contigo.Tenancy/</c>) to the checked-in
    /// script under <c>backend/src/Contigo.Documents.Contracts/Migrations/Scripts/</c>, the same
    /// way <c>DocumentsContractsMigrationScriptTests.ScriptPath</c> does.
    /// <see cref="System.Runtime.CompilerServices.CallerFilePathAttribute"/> resolves at compile
    /// time against the source tree, not the test runner's working directory, so this is stable
    /// across however `dotnet test` is invoked.
    /// </summary>
    private static string ScriptPath(
        [System.Runtime.CompilerServices.CallerFilePath] string here = "") =>
        Path.GetFullPath(Path.Combine(
            Path.GetDirectoryName(here)!, "..", "..",
            "src", "Contigo.Documents.Contracts", "Migrations", "Scripts",
            "documents-contracts.sql"));

    private static async Task<string> ReadScriptAsync()
    {
        var path = ScriptPath();
        Assert.True(
            File.Exists(path),
            $"Migration script not found at {path}. Regenerate with " +
            "`dotnet ef migrations script --idempotent` from src/Contigo.Documents.Contracts.");
        return await File.ReadAllTextAsync(path);
    }

    private static async Task<(bool Enabled, bool Forced)> ReadRowSecurityFlagsAsync(
        NpgsqlConnection connection, string table)
    {
        await using var command = new NpgsqlCommand(
            "SELECT relrowsecurity, relforcerowsecurity FROM pg_class WHERE oid = to_regclass(@table)",
            connection);
        command.Parameters.AddWithValue("table", table);

        await using var reader = await command.ExecuteReaderAsync();
        var hasRow = await reader.ReadAsync();
        Assert.True(
            hasRow,
            $"[ADR-009] Table \"{table}\" was not found in pg_class after applying the " +
            "deployable script.");

        return (reader.GetBoolean(0), reader.GetBoolean(1));
    }

    private static async Task<long> ReadPolicyCountAsync(NpgsqlConnection connection, string table)
    {
        await using var command = new NpgsqlCommand(
            "SELECT count(*) FROM pg_policies WHERE schemaname = 'public' AND tablename = @table",
            connection);
        command.Parameters.AddWithValue("table", table);

        return Convert.ToInt64(await command.ExecuteScalarAsync());
    }
}
