#!/usr/bin/env python3
"""Fail-closed preflight for a nightly execution slice.

Slice launch (--slice) checks only what is needed to *start Helix*
(GitHub auth/org, repos after r0-a, previous HITL). Azure and HCP are
**per-task**: a missing CONTIGO_AZURE_SUBSCRIPTION_ID must not stop a
GitHub-only or file-only task. Those tasks run; the task that actually
calls az / terraform apply / HCP emits HALTED via --task.

Usage (cwd = .helix):
  python scripts/check_slice_prereqs.py --slice r0-a
  python scripts/check_slice_prereqs.py --from-current
  python scripts/check_slice_prereqs.py --task reports/workitems/.../task-01.md
  python scripts/check_slice_prereqs.py --check azure_subscription
  python scripts/check_slice_prereqs.py --record-hitl r0-a
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

HERE = Path(__file__).resolve().parents[1]
GATES = HERE / "reports" / "plan" / "gates"
CURRENT = HERE / "reports" / "plan" / "slice.current.yaml"
MANIFEST = HERE / "reports" / "plan" / "slices" / "MANIFEST.yaml"
ENV_FILE = HERE / ".env"

GENERIC_SUB_NAME = re.compile(
    r"^(azure subscription\s+\d+|free trial|azure for students|"
    r"microsoft azure(?: enterprise)?(?: demo)?|n/a)$",
    re.I,
)
TRIAL_QUOTA = re.compile(
    r"freetrial|students_|azurepass|azure_pass|msdn_201",
    re.I,
)


def _load_dotenv(path: Path) -> None:
    """Fill os.environ from .env without overriding a non-empty existing var."""
    if not path.is_file():
        return
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        name = name.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
            continue
        existing = os.environ.get(name)
        if existing:
            continue
        os.environ[name] = value


_load_dotenv(ENV_FILE)
DEFAULT_OWNER = (
    os.environ.get("CONTIGO_GITHUB_OWNER")
    or os.environ.get("CONTIGO_GITHUB_ORG")
    or "lucalamalfa91"
)
DEFAULT_REPO = os.environ.get("CONTIGO_GITHUB_REPO", "contigo")
DEFAULT_ORG = DEFAULT_OWNER
REPOS = (DEFAULT_REPO,)

def _load_slice_table() -> dict[str, dict]:
    """HITL chain from cut_nightly_slices.py MANIFEST (JSON subset written as YAML)."""
    if not MANIFEST.is_file():
        raise SystemExit(
            "missing reports/plan/slices/MANIFEST.yaml — run "
            "python scripts/cut_nightly_slices.py"
        )
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    table: dict[str, dict] = {}
    for row in data["slices"]:
        table[row["id"]] = {
            "title": row["title"],
            "previous": row["previous"],
            "checks": list(row["checks"]),
        }
    return table


# previous=None means first slice (no HITL stamp required). Regenerated by the cutter.
SLICES: dict[str, dict] = _load_slice_table()

HOW = {
    "github_auth": "gh auth login  (scopes: repo, public_repo)",
    "github_org": (
        f"GitHub owner '{DEFAULT_OWNER}' must exist (user account lucalamalfa91, "
        "not a Contigo org). Override with CONTIGO_GITHUB_OWNER."
    ),
    "github_repos": (
        f"Public repository {DEFAULT_OWNER}/{DEFAULT_REPO} must exist "
        "(https://github.com/lucalamalfa91/contigo). "
        "Override with CONTIGO_GITHUB_OWNER / CONTIGO_GITHUB_REPO."
    ),
    "azure_subscription": (
        "Create a dedicated Contigo subscription (name must contain 'contigo'), "
        "put its GUID in .env as CONTIGO_AZURE_SUBSCRIPTION_ID, then "
        "`az account set --subscription <id>`. A leftover default such as "
        "'Azure subscription 1' or a Free Trial is not accepted."
    ),
    "hcp_terraform": (
        "Create a HashiCorp Cloud org. Then `terraform login` "
        "or set TF_TOKEN / TFE_TOKEN. Workspaces contigo-dev / contigo-demo "
        "are created by the slice; the HCP account must exist now."
    ),
    "hitl_previous": (
        "After the morning HITL of the previous slice, stamp it: "
        "python scripts/check_slice_prereqs.py --record-hitl <previous-id>"
    ),
}


def _run(cmd: list[str], timeout: int = 45) -> tuple[int, str]:
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except FileNotFoundError:
        return 127, f"command not found: {cmd[0]}"
    except subprocess.TimeoutExpired:
        return 124, f"timed out: {' '.join(cmd)}"
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode, out.strip()


def check_github_auth() -> tuple[bool, str]:
    code, out = _run(["gh", "auth", "status"])
    if code != 0:
        return False, out or "gh auth status failed"
    m = re.search(r"Logged in to github.com account (\S+)", out)
    who = m.group(1) if m else "ok"
    return True, who


def check_github_org() -> tuple[bool, str]:
    code, out = _run(["gh", "api", f"users/{DEFAULT_OWNER}", "--jq", ".login"])
    if code != 0:
        return False, out or f"user {DEFAULT_OWNER} not found"
    login = out.splitlines()[-1].strip().strip('"')
    return True, login


def check_github_repos() -> tuple[bool, str]:
    code, out = _run(
        [
            "gh",
            "api",
            f"repos/{DEFAULT_OWNER}/{DEFAULT_REPO}",
            "--jq",
            "{full_name:.full_name, visibility:.visibility}",
        ]
    )
    if code != 0:
        return False, f"missing repo: {DEFAULT_OWNER}/{DEFAULT_REPO}"
    try:
        data = json.loads(out.strip())
    except json.JSONDecodeError:
        return False, f"could not parse {DEFAULT_OWNER}/{DEFAULT_REPO} detail"
    if data.get("visibility") != "public":
        return False, f"{DEFAULT_OWNER}/{DEFAULT_REPO} must be public"
    return True, f"{DEFAULT_OWNER}/{DEFAULT_REPO} (public)"


def _az_bin() -> str:
    if os.name == "nt":
        return "az.cmd"
    return "az"


def _az(args: list[str], timeout: int = 45) -> tuple[int, str]:
    code, out = _run([_az_bin(), *args], timeout=timeout)
    if code == 127:
        code, out = _run(["az", *args], timeout=timeout)
    return code, out


def _az_json(args: list[str]) -> tuple[str | None, Any]:
    code, out = _az([*args, "-o", "json"])
    if code != 0:
        return out or "az failed", None
    start_obj = out.find("{")
    start_arr = out.find("[")
    starts = [i for i in (start_obj, start_arr) if i >= 0]
    if not starts:
        return "az did not return JSON", None
    try:
        return None, json.loads(out[min(starts) :])
    except json.JSONDecodeError:
        return "az did not return JSON", None


def _summarize_subs(subs: list[dict]) -> str:
    if not subs:
        return "no subscriptions visible to this login"
    lines = []
    for s in subs:
        name = s.get("name") or "?"
        sid = s.get("id") or "?"
        state = s.get("state") or "?"
        default = " (default)" if s.get("isDefault") else ""
        lines.append(f"{name}  {sid}  [{state}]{default}")
    return "visible subscriptions: " + "; ".join(lines)


def check_azure_subscription() -> tuple[bool, str]:
    pinned = (os.environ.get("CONTIGO_AZURE_SUBSCRIPTION_ID") or "").strip()
    err, listed = _az_json(["account", "list", "--all"])
    if listed is None:
        err, listed = _az_json(["account", "list"])
    subs: list[dict] = listed if isinstance(listed, list) else []
    summary = _summarize_subs(subs)

    if not pinned:
        return False, (
            "CONTIGO_AZURE_SUBSCRIPTION_ID is unset. Logging in is not enough: "
            "pin the Contigo subscription GUID in .env. " + summary
        )
    try:
        pinned = str(uuid.UUID(pinned))
    except ValueError:
        return False, (
            f"CONTIGO_AZURE_SUBSCRIPTION_ID={pinned!r} is not a GUID. " + summary
        )

    match = next((s for s in subs if str(s.get("id") or "").lower() == pinned.lower()), None)
    if match is None:
        err_show, data = _az_json(["account", "show", "--subscription", pinned])
        if not isinstance(data, dict):
            return False, (
                f"subscription {pinned} not in this tenant. {err or err_show or ''} "
                + summary
            )
        match = data
    else:
        _err_detail, detail = _az_json(["account", "show", "--subscription", pinned])
        if isinstance(detail, dict):
            match = {**match, **detail}

    name = str(match.get("name") or "").strip() or "?"
    state = str(match.get("state") or "")
    quota = str(match.get("quotaId") or "")
    policies = match.get("subscriptionPolicies") or {}
    if not quota and isinstance(policies, dict):
        quota = str(policies.get("quotaId") or "")
    spending = ""
    if isinstance(policies, dict):
        spending = str(policies.get("spendingLimit") or "")
    if not spending:
        spending = str(match.get("spendingLimit") or "")

    if state and state.lower() != "enabled":
        return False, f"{name} ({pinned}) state is {state}, need Enabled. " + summary
    if GENERIC_SUB_NAME.match(name):
        return False, (
            f"{name} ({pinned}) is a default/placeholder subscription, not Contigo. "
            "Create a dedicated subscription whose name contains 'contigo'. " + summary
        )
    if "contigo" not in name.lower():
        return False, (
            f"{name} ({pinned}) name does not contain 'contigo'. "
            "Rename it or create a Contigo-named subscription so the pin cannot "
            "silently target a leftover free/default sub. " + summary
        )
    if TRIAL_QUOTA.search(quota) or spending.lower() in {"on", "currentperiodoff"}:
        return False, (
            f"{name} ({pinned}) looks like a trial/capped offer "
            f"(quotaId={quota or '?'}, spendingLimit={spending or '?'}). "
            "Contigo needs a pay-as-you-go (or EA/CSP) subscription in westeurope. "
            + summary
        )

    err_cur, current = _az_json(["account", "show"])
    if current is None:
        return False, (err_cur or "az account show failed") + ". " + summary
    current_id = str(current.get("id") or "")
    if current_id.lower() != pinned.lower():
        return False, (
            f"az default is {current.get('name')} ({current_id}), not the pinned "
            f"Contigo sub {name} ({pinned}). Run: az account set --subscription {pinned}"
        )
    return True, f"{name} ({pinned})"


def _hcp_cred_paths() -> list[Path]:
    home = Path.home()
    paths = [home / ".terraform.d" / "credentials.tfrc.json"]
    appdata = os.environ.get("APPDATA")
    if appdata:
        paths.append(Path(appdata) / "terraform.d" / "credentials.tfrc.json")
    return paths


def check_hcp_terraform() -> tuple[bool, str]:
    for var in ("TF_TOKEN", "TFE_TOKEN", "TF_API_TOKEN"):
        if os.environ.get(var):
            return True, f"{var} is set"
    for path in _hcp_cred_paths():
        if path.is_file() and path.stat().st_size > 2:
            return True, f"credentials file {path}"
    return False, "no TF_TOKEN/TFE_TOKEN and no terraform login credentials file"


def check_hitl_previous(previous: str | None) -> tuple[bool, str]:
    if not previous:
        return True, "first slice — no previous HITL"
    stamp = GATES / f"{previous}.hitl-ok"
    if stamp.is_file():
        return True, str(stamp.relative_to(HERE))
    return False, (
        f"missing {stamp.relative_to(HERE)} — morning HITL of {previous} not stamped. "
        f"python scripts/check_slice_prereqs.py --record-hitl {previous}"
    )


CheckFn = Callable[[], tuple[bool, str]]


def _dispatch(name: str, previous: str | None) -> tuple[bool, str]:
    if name == "hitl_previous":
        return check_hitl_previous(previous)
    fns: dict[str, CheckFn] = {
        "github_auth": check_github_auth,
        "github_org": check_github_org,
        "github_repos": check_github_repos,
        "azure_subscription": check_azure_subscription,
        "hcp_terraform": check_hcp_terraform,
    }
    fn = fns.get(name)
    if fn is None:
        return False, f"unknown check '{name}'"
    return fn()


def slice_id_from_current() -> str:
    if not CURRENT.is_file():
        raise SystemExit("ERROR: reports/plan/slice.current.yaml is missing")
    text = CURRENT.read_text(encoding="utf-8")
    m = re.search(r"^waveId:\s*(\S+)", text, re.M)
    if not m:
        raise SystemExit("ERROR: slice.current.yaml has no waveId")
    wave_id = m.group(1)
    if wave_id in ("placeholder", "nightly-slice-unset"):
        raise SystemExit(
            "ERROR: slice.current.yaml is unset — launch with -Slice <id>"
        )
    tail = wave_id.rsplit("-", 2)
    # wave-v1-night-r0-a → r0-a
    if len(wave_id) >= 4 and re.search(r"r\d+-[a-z]$", wave_id):
        sid = re.search(r"(r\d+-[a-z])$", wave_id)
        if sid:
            return sid.group(1)
    raise SystemExit(f"ERROR: cannot parse slice id from waveId {wave_id}")


def record_hitl(slice_id: str) -> int:
    if slice_id not in SLICES:
        print(f"ERROR: unknown slice '{slice_id}'", file=sys.stderr)
        return 1
    GATES.mkdir(parents=True, exist_ok=True)
    stamp = GATES / f"{slice_id}.hitl-ok"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    stamp.write_text(
        f"slice: {slice_id}\nstamped_at: {now}\n",
        encoding="utf-8",
    )
    print(f"HITL stamp written: {stamp.relative_to(HERE)}")
    return 0


FRONTMATTER_RE = re.compile(r"^---\r?\n(.*?)\r?\n---", re.S)


def requires_from_task(path: Path) -> list[str]:
    """Read optional `requires:` from task YAML frontmatter. Missing → []."""
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        return []
    fm = m.group(1)
    inline = re.search(r"^requires:\s*\[([^\]]*)\]\s*$", fm, re.M)
    if inline:
        inner = inline.group(1).strip()
        if not inner:
            return []
        return [p.strip().strip("'\"") for p in inner.split(",") if p.strip()]
    block = re.search(r"^requires:\s*$", fm, re.M)
    if not block:
        return []
    names: list[str] = []
    for line in fm[block.end() :].splitlines():
        if not line.strip():
            continue
        dm = re.match(r"^\s+-\s+(\S+)\s*$", line)
        if dm:
            names.append(dm.group(1).strip().strip("'\""))
            continue
        break
    return names


def run_named_checks(
    names: list[str],
    *,
    previous: str | None,
    heading: str,
    fail_note: str,
    retry_lines: list[str] | None = None,
) -> int:
    if not names:
        print("=" * 72)
        print(f"{heading} OK  (this task declares no extra cloud prereqs)")
        print("=" * 72)
        return 0

    results: list[tuple[str, bool, str]] = []
    for name in names:
        ok, detail = _dispatch(name, previous)
        results.append((name, ok, detail))

    failed = [(n, d) for n, ok, d in results if not ok]
    passed = [(n, d) for n, ok, d in results if ok]

    print("=" * 72)
    if failed:
        print(f"{heading} FAILED")
        print(fail_note)
    else:
        print(f"{heading} OK")
    print("=" * 72)
    print()
    if failed:
        print(f"Missing {len(failed)} of {len(results)} prerequisites:")
        print()
        for name, detail in failed:
            print(f"  FAIL  {name}")
            print(f"        {detail}")
            print(f"        How: {HOW.get(name, '')}")
            print()
    if passed:
        print("Passed:")
        for name, detail in passed:
            print(f"  PASS  {name}  - {detail}")
        print()
    if failed:
        if retry_lines:
            print("Fix the FAIL items, then re-run:")
            for line in retry_lines:
                print(f"  {line}")
        return 1
    return 0


def run_task_checks(task_arg: str) -> int:
    path = Path(task_arg)
    if not path.is_absolute():
        path = HERE / path
    if not path.is_file():
        print(f"ERROR: task file not found: {task_arg}", file=sys.stderr)
        return 1
    names = requires_from_task(path)
    try:
        rel = path.relative_to(HERE)
    except ValueError:
        rel = path
    return run_named_checks(
        names,
        previous=None,
        heading=f"TASK PRE-FLIGHT  {rel}",
        fail_note=(
            "This task cannot run without the listed credentials. Last line "
            "HALTED — do not invent a workaround. Other tasks in the slice "
            "that do not declare these requires: keep running."
        ),
        retry_lines=[
            f"py -3 scripts/check_slice_prereqs.py --task {rel.as_posix()}",
        ],
    )


def run_checks(slice_id: str) -> int:
    spec = SLICES.get(slice_id)
    if spec is None:
        print(f"ERROR: unknown slice '{slice_id}'", file=sys.stderr)
        print("  known:", ", ".join(SLICES), file=sys.stderr)
        return 1

    title = spec["title"]
    previous = spec["previous"]
    names: list[str] = list(spec["checks"])
    results: list[tuple[str, bool, str]] = []
    for name in names:
        ok, detail = _dispatch(name, previous)
        results.append((name, ok, detail))

    failed = [(n, d) for n, ok, d in results if not ok]
    passed = [(n, d) for n, ok, d in results if ok]

    print("=" * 72)
    if failed:
        print(f"SLICE PRE-FLIGHT FAILED  {slice_id}  ({title})")
        print("Helix execution-fanout was NOT started.")
    else:
        print(f"SLICE PRE-FLIGHT OK  {slice_id}  ({title})")
    print("=" * 72)
    print()
    if failed:
        print(f"Missing {len(failed)} of {len(results)} human/operator prerequisites:")
        print()
        for name, detail in failed:
            print(f"  FAIL  {name}")
            print(f"        {detail}")
            print(f"        How: {HOW.get(name, '')}")
            print()
    if passed:
        print("Passed:")
        for name, detail in passed:
            print(f"  PASS  {name}  - {detail}")
        print()
    if failed:
        print("Fix the FAIL items, then re-run:")
        print(f"  ./run.ps1 -Max -Slice {slice_id} -o execution-fanout")
        print(f"  ./run.sh  --max --slice {slice_id} -o execution-fanout")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Fail-closed slice / per-task prerequisite check"
    )
    parser.add_argument("--slice", help="slice id, e.g. r0-a")
    parser.add_argument(
        "--from-current",
        action="store_true",
        help="read slice id from reports/plan/slice.current.yaml",
    )
    parser.add_argument(
        "--task",
        metavar="PATH",
        help="work-item path; run only its frontmatter requires:",
    )
    parser.add_argument(
        "--check",
        action="append",
        metavar="NAME",
        help="run a named check (repeatable), e.g. azure_subscription",
    )
    parser.add_argument(
        "--record-hitl",
        metavar="SLICE",
        help="stamp morning HITL so the next slice can launch",
    )
    args = parser.parse_args()
    os.chdir(HERE)

    if args.record_hitl:
        return record_hitl(args.record_hitl.lower())

    if args.task:
        return run_task_checks(args.task)

    if args.check:
        return run_named_checks(
            args.check,
            previous=None,
            heading="CHECK  " + ", ".join(args.check),
            fail_note="Last line HALTED — do not work around a missing cloud credential.",
        )

    slice_id = (args.slice or "").lower()
    if args.from_current or not slice_id:
        slice_id = slice_id_from_current() if not slice_id else slice_id
    return run_checks(slice_id)


if __name__ == "__main__":
    raise SystemExit(main())
