using Contigo.Documents.Contracts.Domain;
using Npgsql;
using Pgvector;
using Testcontainers.PostgreSql;

namespace Contigo.Documents.Contracts.Tests;

/// <summary>
/// Proves the Definition of Done for task E01/F04/US02/T02 (us-02-relational-store): the
/// *deployable* migration artifact applies. Task T01 already proved
/// <c>DbContext.Database.MigrateAsync()</c> works end to end
/// (<see cref="DocumentsContractsMigrationTests"/>); this class proves the literal, checked-in
/// idempotent SQL script (<c>Migrations/Scripts/documents-contracts.sql</c>, generated by
/// <c>dotnet ef migrations script --idempotent</c>) applies cleanly to a bare Postgres+pgvector
/// server via plain Npgsql — no <c>DocumentsContractsDbContext</c>, no EF Core runtime
/// migrator, no <c>DocumentsContractsDbContextOptions</c> anywhere in the loop. This is the
/// exact artifact an operator or a CI/CD deploy step would run (e.g. `psql -f`) against a fresh
/// `dev`/`demo` server, independently of the application ever starting.
/// </summary>
public sealed class DocumentsContractsMigrationScriptTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder("pgvector/pgvector:pg16")
        .Build();

    public Task InitializeAsync() => _postgres.StartAsync();

    public Task DisposeAsync() => _postgres.DisposeAsync().AsTask();

    /// <summary>
    /// Walks from this source file
    /// (<c>backend/tests/Contigo.Documents.Contracts.Tests/</c>) to the checked-in script under
    /// <c>backend/src/Contigo.Documents.Contracts/Migrations/Scripts/</c>.
    /// <see cref="System.Runtime.CompilerServices.CallerFilePathAttribute"/> resolves at compile
    /// time against the source tree, not the test runner's working directory or its `bin/`
    /// output, so this is stable across however `dotnet test` is invoked.
    /// </summary>
    private static string ScriptPath(
        [System.Runtime.CompilerServices.CallerFilePath] string here = "") =>
        Path.GetFullPath(Path.Combine(
            Path.GetDirectoryName(here)!, "..", "..",
            "src", "Contigo.Documents.Contracts", "Migrations", "Scripts",
            "documents-contracts.sql"));

    private static async Task<string> ReadScriptAsync()
    {
        var path = ScriptPath();
        Assert.True(
            File.Exists(path),
            $"Migration script not found at {path}. Regenerate with " +
            "`dotnet ef migrations script --idempotent` from src/Contigo.Documents.Contracts " +
            "(task E01/F04/US02/T02).");
        return await File.ReadAllTextAsync(path);
    }

    [Fact]
    public async Task Idempotent_script_applies_to_a_bare_postgres_and_is_safe_to_rerun()
    {
        var script = await ReadScriptAsync();
        Assert.Contains("CREATE EXTENSION IF NOT EXISTS vector", script, StringComparison.Ordinal);

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();

        // Two applies of the same script against a server that starts with nothing but the
        // pgvector image's defaults — no prior EF Core migrate call anywhere in this test.
        await using (var first = new NpgsqlCommand(script, connection))
        {
            await first.ExecuteNonQueryAsync();
        }

        await using (var second = new NpgsqlCommand(script, connection))
        {
            await second.ExecuteNonQueryAsync();
        }

        await using var verify = new NpgsqlCommand(
            "SELECT count(*) FROM \"__EFMigrationsHistory\" WHERE migration_id = @id", connection);
        verify.Parameters.AddWithValue("id", "20260902205243_Initial");
        var recordedCount = (long)(await verify.ExecuteScalarAsync())!;
        Assert.Equal(1L, recordedCount);
    }

    [Fact]
    public async Task Script_created_vector_column_is_usable_by_plain_npgsql_with_no_ef_core_involved()
    {
        var script = await ReadScriptAsync();

        await using (var setupConnection = new NpgsqlConnection(_postgres.GetConnectionString()))
        {
            await setupConnection.OpenAsync();
            await using var apply = new NpgsqlCommand(script, setupConnection);
            await apply.ExecuteNonQueryAsync();
        }

        // A bespoke data source with only the base Pgvector package's UseVector() wired in —
        // deliberately not DocumentsContractsDbContextOptions — so this proves the `vector`
        // column the SQL script created is usable by any pgvector-aware Postgres client, not
        // something that only works because of this solution's own EF Core configuration.
        var dataSourceBuilder = new NpgsqlDataSourceBuilder(_postgres.GetConnectionString());
        dataSourceBuilder.UseVector();
        await using var dataSource = dataSourceBuilder.Build();
        await using var connection = await dataSource.OpenConnectionAsync();

        var id = Guid.NewGuid();
        var original = new float[1536];
        for (var i = 0; i < original.Length; i++)
        {
            original[i] = i * 0.001f;
        }

        await using (var insert = new NpgsqlCommand(
            "INSERT INTO embedding (id, source_type, source_id, chunk_index, chunk_text, vector, " +
            "model, created_at, tenant_id) VALUES " +
            "(@id, @source_type, @source_id, @chunk_index, @chunk_text, @vector, @model, " +
            "@created_at, @tenant_id)",
            connection))
        {
            insert.Parameters.AddWithValue("id", id);
            insert.Parameters.AddWithValue("source_type", "Document");
            insert.Parameters.AddWithValue("source_id", Guid.NewGuid());
            insert.Parameters.AddWithValue("chunk_index", 0);
            insert.Parameters.AddWithValue("chunk_text", "script-only round trip, no DbContext involved");
            insert.Parameters.AddWithValue("vector", new Vector(original));
            insert.Parameters.AddWithValue("model", "text-embedding-3-small");
            insert.Parameters.AddWithValue("created_at", DateTimeOffset.UtcNow);
            insert.Parameters.AddWithValue("tenant_id", Guid.NewGuid());
            await insert.ExecuteNonQueryAsync();
        }

        await using var select = new NpgsqlCommand(
            "SELECT vector_dims(vector), (vector <-> vector) FROM embedding WHERE id = @id", connection);
        select.Parameters.AddWithValue("id", id);
        await using var reader = await select.ExecuteReaderAsync();
        Assert.True(await reader.ReadAsync());
        Assert.Equal(Embedding.VectorDimensions, reader.GetInt32(0));
        Assert.Equal(0.0, reader.GetDouble(1), precision: 6);
    }
}
