// <auto-generated />
using System;
using Contigo.Documents.Contracts.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Contigo.Documents.Contracts.Migrations
{
    [DbContext(typeof(DocumentsContractsDbContext))]
    [Migration("20260904135028_AddStagedExtractionEvidence")]
    partial class AddStagedExtractionEvidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Clause", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClauseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clause_type");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedValue")
                        .HasColumnType("text")
                        .HasColumnName("normalized_value");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<string>("SourceSpan")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_span");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_clause");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_clause_contract_id");

                    b.HasIndex("SourceDocumentId")
                        .HasDatabaseName("ix_clause_source_document_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_clause_tenant_id");

                    b.ToTable("clause", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AnnualSpend")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("annual_spend");

                    b.Property<bool>("AutoRenewal")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renewal");

                    b.Property<DateOnly?>("CancellationDeadline")
                        .HasColumnType("date")
                        .HasColumnName("cancellation_deadline");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("GoverningLaw")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("governing_law");

                    b.Property<Guid?>("ParentContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_contract_id");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("payment_terms");

                    b.Property<int?>("RenewalTermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("renewal_term_months");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("TotalContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_contract_value");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_contract");

                    b.HasIndex("ParentContractId")
                        .HasDatabaseName("ix_contract_parent_contract_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_contract_supplier_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contract_tenant_id");

                    b.ToTable("contract", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.ContractLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AnnualCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("annual_cost");

                    b.Property<string>("BillingPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("billing_period");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount");

                    b.Property<decimal?>("ListPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("list_price");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sku");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<string>("SourceSpan")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_span");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_cost");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_contract_line_item");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_line_item_contract_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_contract_line_item_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contract_line_item_tenant_id");

                    b.ToTable("contract_line_item", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.ContractVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("change_reason");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_contract_version");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contract_version_tenant_id");

                    b.HasIndex("ContractId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_contract_version_contract_id_version_number");

                    b.ToTable("contract_version", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.CorrectionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CorrectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_at");

                    b.Property<string>("CorrectedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("corrected_by");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("text")
                        .HasColumnName("previous_value");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_entity_id");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_entity_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_correction_history");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_correction_history_tenant_id");

                    b.HasIndex("TargetEntityType", "TargetEntityId")
                        .HasDatabaseName("ix_correction_history_target_entity_type_target_entity_id");

                    b.ToTable("correction_history", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("checksum");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mime_type");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("processing_status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_document_contract_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_document_tenant_id");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("checksum");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_document_version");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_document_version_tenant_id");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_document_version_document_id_version_number");

                    b.ToTable("document_version", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Embedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("vector");

                    b.HasKey("Id")
                        .HasName("pk_embedding");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_embedding_tenant_id");

                    b.HasIndex("SourceType", "SourceId")
                        .HasDatabaseName("ix_embedding_source_type_source_id");

                    b.ToTable("embedding", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.ExtractionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ExtractionJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("extraction_job_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_name");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<string>("SourceSpan")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_span");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_extraction_evidence");

                    b.HasIndex("ExtractionJobId")
                        .HasDatabaseName("ix_extraction_evidence_extraction_job_id");

                    b.HasIndex("SourceDocumentId")
                        .HasDatabaseName("ix_extraction_evidence_source_document_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_extraction_evidence_tenant_id");

                    b.HasIndex("ContractId", "FieldName")
                        .HasDatabaseName("ix_extraction_evidence_contract_id_field_name");

                    b.ToTable("extraction_evidence", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.ExtractionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text")
                        .HasColumnName("error_detail");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_id");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_extraction_job");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_extraction_job_document_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_extraction_job_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_extraction_job_tenant_id");

                    b.ToTable("extraction_job", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Obligation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Criticality")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("criticality");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("ObligationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("obligation_type");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("party");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<string>("SourceSpan")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_span");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_obligation");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_obligation_contract_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_obligation_due_date");

                    b.HasIndex("SourceDocumentId")
                        .HasDatabaseName("ix_obligation_source_document_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_obligation_tenant_id");

                    b.ToTable("obligation", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClauseId")
                        .HasColumnType("uuid")
                        .HasColumnName("clause_id");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("IdentifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("identified_at");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("risk_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<string>("SourceSpan")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_span");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_risk");

                    b.HasIndex("ClauseId")
                        .HasDatabaseName("ix_risk_clause_id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_risk_contract_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_risk_tenant_id");

                    b.ToTable("risk", (string)null);
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Clause", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clause_contract_contract_id");

                    b.HasOne("Contigo.Documents.Contracts.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clause_document_source_document_id");
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Contract", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ParentContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contract_contract_parent_contract_id");
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.ContractLineItem", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_line_item_contract_contract_id");
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.ContractVersion", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_version_contract_contract_id");
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Document", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_document_contract_contract_id");
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.DocumentVersion", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_version_document_document_id");
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.ExtractionEvidence", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extraction_evidence_contract_contract_id");

                    b.HasOne("Contigo.Documents.Contracts.Domain.ExtractionJob", null)
                        .WithMany()
                        .HasForeignKey("ExtractionJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_extraction_evidence_extraction_job_extraction_job_id");

                    b.HasOne("Contigo.Documents.Contracts.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_extraction_evidence_document_source_document_id");
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.ExtractionJob", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extraction_job_document_document_id");
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Obligation", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obligation_contract_contract_id");

                    b.HasOne("Contigo.Documents.Contracts.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_obligation_document_source_document_id");
                });

            modelBuilder.Entity("Contigo.Documents.Contracts.Domain.Risk", b =>
                {
                    b.HasOne("Contigo.Documents.Contracts.Domain.Clause", null)
                        .WithMany()
                        .HasForeignKey("ClauseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_risk_clause_clause_id");

                    b.HasOne("Contigo.Documents.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_risk_contract_contract_id");
                });
#pragma warning restore 612, 618
        }
    }
}
